### PR TITLE
Slicersalt 2020 07 08 23d1746 Enable ShapePopulationViewer to visualize S-Reps

### PR DESCRIPTION
**Pull request by yehan0223**
To address #2 
The up spokes, down spokes, crest spokes, medial mesh and fold curve are assigned with different point data named cellType for coloring in ShapePopulationViewer. Feel free to let me know what you think. @bpaniagua @vicory 
Screenshot from 2021-04-20 21-51-20

### CODE REVIEW

**Comment by bpaniagua** [comment]
Hi YeHan,

It looks really good! Do you know how to create custom color maps? We could use the existing color map scheme to set up custom colors in the spokes. Overall it looks promising. @vicory can you please QA this PR?

**Comment by yehan0223** [comment]
> Hi YeHan,
> 
> It looks really good! Do you know how to create custom color maps? We could use the existing color map scheme to set up custom colors in the spokes. Overall it looks promising. @vicory can you please QA this PR?

For now, I don't know how to create a custom color map. Maybe we can do it by adding more pre-defined color map spectra, or enabling users to specified per-point color. The first approach should be easier to implement. I feel this could be really useful for many use cases, shall we create a separate issue for creating custom color maps?

**Comment by yehan0223** [comment]
> > Hi YeHan,
> > It looks really good! Do you know how to create custom color maps? We could use the existing color map scheme to set up custom colors in the spokes. Overall it looks promising. @vicory can you please QA this PR?
> 
> For now, I don't know how to create a custom color map. Maybe we can do it by adding more pre-defined color map spectra, or enabling users to specified per-point color. The first approach should be easier to implement. I feel this could be really useful for many use cases, shall we create a separate issue for creating custom color maps?

Welp, just found out that we can directly specify per-point color by clicking the color square next to the point idx, I guess I should try to pre-define the per-point color during the loading process of the SRep files?

**Comment by yehan0223** [comment]
Screenshot from 2021-04-21 10-34-29
This should look more like what we have in the initializer. I can also convert the medial mesh into wireframe if needed. I will put a customized color map under the resource folder and load it during the loading process for SReps. Here is the one I use for the pic above 
`<?xml version="1.0" encoding="UTF-8"?>
<SPVColorMap description="ShapePopulationViewer Color Map configuration" version="1.0">
    <colormap name="222" points="5">
        <colorpoint index="0">
            <position>0</position>
            <R>1</R>
            <G>0</G>
            <B>1</B>
        </colorpoint>
        <colorpoint index="1">
            <position>0.25</position>
            <R>0</R>
            <G>0.666667</G>
            <B>0</B>
        </colorpoint>
        <colorpoint index="2">
            <position>0.5</position>
            <R>1</R>
            <G>1</G>
            <B>0</B>
        </colorpoint>
        <colorpoint index="3">
            <position>0.75</position>
            <R>1</R>
            <G>1</G>
            <B>0</B>
        </colorpoint>
        <colorpoint index="4">
            <position>1</position>
            <R>0.333333</R>
            <G>1</G>
            <B>1</B>
        </colorpoint>
    </colormap>
</SPVColorMap>`

**Comment by bpaniagua** [comment]
Yes! This is really a great direction!

**Comment by yehan0223** [comment]
Now, the new colormap is loaded automatically when ShapePopulationViewer reads SReps.
Screenshot from 2021-04-21 18-48-59

**Comment by yehan0223** [comment]
One thing I am not sure about is the ShapePopulationViewer.cxx, it seems to be outside the project. My guess is that it requires us to build the superbuild and ShapePopulationViewer is then compiled into an independent application. I will try to make the superbuild to work. For now, the slicer module works without any issue on my local machine.

**Comment by jcfr** [comment]
>ShapePopulationViewer.cxx, it seems to be outside the project

The project can be built in two ways:
(1) Independent executable (or CLI) accepting command line parameters and displaying its user interface in a dedicated process
(2) Slicer loadable module showing the user interface in Slicer and running withing the Slicer process

In https://github.com/NIRALUser/ShapePopulationViewer#build-instructions, (1) is referred as the standalone build and (2) as the Slicer extension build.

`ShapePopulationViewer.cxx` corresponds to the code responsible for implementing (1)

**Comment by yehan0223** [comment]
> > ShapePopulationViewer.cxx, it seems to be outside the project
> 
> The project can be built in two ways:
> (1) Independent executable (or CLI) accepting command line parameters and displaying its user interface in a dedicated process
> (2) Slicer loadable module showing the user interface in Slicer and running withing the Slicer process
> 
> In https://github.com/NIRALUser/ShapePopulationViewer#build-instructions, (1) is referred as the standalone build and (2) as the Slicer extension build.
> 
> `ShapePopulationViewer.cxx` corresponds to the code responsible for implementing (1)

Hi @jcfr , thanks for the helpful info. I was trying to get (1) to work without building (2), and I figured out some of the issues. Basically there are `unset`s in the   SuperBuild/*.cmake that prevents loading existing builds. The change I made is in below.
[diff-superbuild.txt](https://github.com/slicersalt/ShapePopulationViewer/files/6354887/diff-superbuild.txt)
Meanwhile, there also is a remaining issue that prevents the final install step for ShapePopulationViewer. I paste the error info below and it seems like the install directory is not set up correctly, any suggestion? FYI, I build it on Ubuntu 20.04
`[38/41] Performing install step for 'ShapePopulationViewer'
/bin/sh: 1: : Permission denied
[38/41] Forcing configure step for 'ShapePopulationViewer'
FAILED: ShapePopulationViewer-prefix/src/ShapePopulationViewer-stamp/ShapePopulationViewer-install 
cd /home/yehan/Kitware/ShapePopulationViewer-debug/ShapePopulationViewer-build && "" "" && /home/yehan/Support/cmake-3.18.4-Linux-x86_64/bin/cmake -E touch /home/yehan/Kitware/ShapePopulationViewer-debug/ShapePopulationViewer-prefix/src/ShapePopulationViewer-stamp/ShapePopulationViewer-install
[40/41] Forcing configure step for 'ShapePopulationViewer'
ninja: build stopped: subcommand failed.
`

**Comment by yehan0223** [comment]
@jcfr regarding the `unset` for vtk_dir and itk_dir, I feel the initial purpose was to make sure the packages are the same as the ones used for building Slicer if user builds the Slicer loadable module. If so, the proper logic maybe:
1. if building only loadable module, unset directories and build against ones under the Slicer-build.
2. if building only independent executable, allow users to specify existing ITK/VTK builds.
3. if building both, follow 1.
Any comments?

**Review by bpaniagua — APPROVED** [review]
looks good to me, ok to merge!

**Comment by jcfr** [comment]
There are few scenarios:
* (a) build against Slicer build tree (case (2))
* (b) build against specific build tree of each dependency (case (1))
* (c) build against dependencies found on the system

> thanks for the helpful info. I was trying to get (1) to work without building (2), and I figured out some of the issues. 

The `unset` calls are here to handle (c), if you would like to build against specific build tree of VTK/Qt5/... simply pass the corresponding options (`-DVTK_DIR:PATH=/path/to/VTK-build-or-install`, ....)

**Pull request merged**
